# Generated by Django 4.1.7 on 2023-04-01 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_id', models.IntegerField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('by', models.CharField(max_length=55)),
                ('descendants', models.IntegerField()),
                ('score', models.IntegerField()),
                ('url', models.URLField(null=True)),
            ],
        ),
    ]
