# Generated by Django 4.1.7 on 2023-04-07 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='by',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
