# fly.toml file generated for hacker-reader-api on 2023-04-02T23:19:26-04:00

app = "hacker-reader-api"
kill_signal = "SIGINT"
kill_timeout = 5
primary_region = "iad"

[deploy]
  release_command = "python manage.py migrate --noinput"

[env]
  PORT = "8000"

[[statics]]
  guest_path = "/code/static"
  url_prefix = "/static/"

[[services]]
  protocol = "tcp"
  internal_port = 8000
  processes = ["app"]

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]
  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
